services:
  db:
    image: postgres:16
    container_name: teccode_pg
    environment:
      POSTGRES_DB: teccode
      POSTGRES_USER: teccode
      POSTGRES_PASSWORD: teccode
    ports:
      - "5432:5432"
    volumes:
      - teccode_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teccode -d teccode"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  teccode_pg_data:
